---

- name: Manage /etc/resolv.conf
  file:
    dest: /etc/resolv.conf
    src: "{{ systemd_resolved_resolv_file }}"
    state: link
    force: yes
  when: systemd_networkd_enable_resolved

- name: Configure systemd-resolved service
  service:
    name: systemd-resolved
    state: "{{ 'started' if systemd_networkd_enable_resolved else omit }}"
    enabled: "{{ systemd_networkd_enable_resolved }}"

# vim: set ts=2 sw=2:
