---

- name: Ensure resolved.conf configuration file
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  when: systemd_networkd_enable_resolved

- name: Manage /etc/resolv.conf
  file:
    dest: /etc/resolv.conf
    src: "{{ systemd_resolved_resolv_file }}"
    state: link
    force: yes
  when: systemd_networkd_enable_resolved

- name: Configure systemd-resolved service
  service:
    name: systemd-resolved
    state: "{{ 'started' if systemd_networkd_enable_resolved else omit }}"
    enabled: "{{ systemd_networkd_enable_resolved }}"

# vim: set ts=2 sw=2:
