---

- name: Configure systemd-resolved service
  service:
    name: systemd-resolved
    state: "{{ 'started' if systemd_networkd_enable_resolved else omit }}"
    enabled: "{{ systemd_networkd_enable_resolved }}"

# vim: set ts=2 sw=2:
